print("___1/24___")
print(55+30)
print("___2/24___")
print(7-3)
print(4*5)
print(5/3)
print("___3/24___")
print(3**8)
print("___4/24___")
print(20//3)
print(20%3)
print("___5/24___")
print(4*5, 4**3, (20-8)*2)
print("___8/24___")
print("Scott+Mary=peace, love and happiness")
print("___9/24___")
print(41%7)
print("___10/24___")
print(35)
print("___11/24___")
print(5%(101%3),(76//3)*4)
print("___12/24___")
Q1=(input("How are you today?"))
Q2=(input("Would you say you are tired?"))
print("was that a yes or a no?")
(input())
Q3=(int(input("What is your favourite number?")))
print("___13/24___")
a=input()
print("My input is " + a)
colour=input("what is your fav colur?")
print("my fav colour is " + colour)
print("My fav colour is" ,colour + ".")
print("my fav colour is" ,colour, ".")
colour=input("What is your fav colour?")
colour2=input("Do you have a second choice?")
print("My fav colour is " + colour + "and" + colour2)
print("My fav colour is" ,colour,"and",colour2, ".")
print("My fav colour is" ,colour,"and",colour2 + ".")
print("___14/24___")
print("Below you will be asked to input a value...")
a=input()
print("My input is " + a + ".")
asking=input("can you please input a value here ->")
print("My inputted value is " + asking + ".")
print("___15/24___")
print(input())
23
print("___16/24___")
a=3
print(a)
print("___17/24___")
print((2**10-3.7)/(95/6+8))
numerator=2**10-3.7
denominator=95/6+8
N=numerator/denominator
print(N)
print("___18/24___")
print('what is your name?')
name=input()
print('Hi ' + name + '!')
print("___20/24___")
a=input()
b=input()
s=a+b
print(s)
print("___21/24___")
num=14
s='hadoop'
que="wroom"
print(s+que)
print("___22/24___")
first='5'
second="7"
print("first * second")
print("___23/24___")
print("My age is...")
age=int(input())
print("Ten years from now my age will be, " + str(age+10))
print("Ten years ago, my age was, " + str(age-10))
print("___24/24___")
num1=int(input())
num2=int(input())
sum=num1+num2
print(sum)
      

