import turtle
wn=turtle.Screen()
alex=turtle.Turtle()

cond = input("what drink do you want? water ,  orange juice , or coffee: ")
if cond == "water":
    alex.penup() #cup
    alex.forward(50)
    alex.pendown()
    alex.left(90)
    alex.backward(90)
    alex.right(90)
    alex.backward(50)
    alex.right(90)
    alex.backward(90)
    alex.forward(20)

    alex.color("black", "blue") #drink
    alex.begin_fill()
    alex.left(90)
    alex.forward(50)
    alex.right(90)
    alex.forward(70)
    alex.right(90)
    alex.forward(50)
    alex.right(90)
    alex.forward(70)
    alex.end_fill()

if cond == "orange juice":
     alex.penup() #cup
     alex.forward(50)
     alex.pendown()
     alex.left(90)
     alex.backward(90)
     alex.right(90)
     alex.backward(50)
     alex.right(90)
     alex.backward(90)
     alex.forward(20)

     alex.color("black", "orange") #drink
     alex.begin_fill()
     alex.left(90)
     alex.forward(50)
     alex.right(90)
     alex.forward(70)
     alex.right(90)
     alex.forward(50)
     alex.right(90)
     alex.forward(70)
     alex.end_fill()

if cond == "coffee":
     alex.penup() #cup
     alex.forward(50)
     alex.pendown()
     alex.left(90)
     alex.backward(90)
     alex.right(90)
     alex.backward(50)
     alex.right(90)
     alex.backward(90)
     alex.forward(20)

     alex.color("black", "brown") #drink
     alex.begin_fill()
     alex.left(90)
     alex.forward(50)
     alex.right(90)
     alex.forward(70)
     alex.right(90)
     alex.forward(50)
     alex.right(90)
     alex.forward(70)
     alex.end_fill()

alex.penup() #new position
alex.right(90)
alex.forward(90)
alex.pendown()

cond = input("Do you want fries? yes or no: ")
if cond == "yes":
    alex.color("black", "red") #container for fries
    alex.begin_fill()
    alex.forward(50)
    alex.left(90)
    alex.backward(70)
    alex.right(90)
    alex.backward(50)
    alex.right(90)
    alex.backward(70)
    alex.end_fill()
    alex.left(90)
    alex.forward(25)
    alex.right(90)
    alex.forward(10)
    alex.left(90)
    alex.color("white")
    alex.begin_fill()
    alex.circle(30)
    alex.end_fill()

    alex.color("black", "yellow") #fries
    alex.begin_fill()
    alex.backward(15)
    alex.left(90)
    alex.forward(30)
    alex.right(90)
    alex.forward(5)
    alex.right(90)
    alex.forward(30)
    alex.left(90)
    alex.left(90)
    alex.forward(30)
    alex.right(90)
    alex.forward(5)
    alex.right(90)
    alex.forward(30)
    alex.left(90)
    alex.left(90)
    alex.forward(30)
    alex.right(90)
    alex.forward(5)
    alex.right(90)
    alex.forward(30)
    alex.left(90)
    alex.left(90)
    alex.forward(30)
    alex.right(90)
    alex.forward(5)
    alex.right(90)
    alex.forward(30)
    alex.left(90)
    alex.left(90)
    alex.forward(30)
    alex.right(90)
    alex.forward(5)
    alex.right(90)
    alex.forward(30)
    alex.left(90)
    alex.left(90)
    alex.forward(30)
    alex.right(90)
    alex.forward(5)
    alex.right(90)
    alex.forward(30)
    alex.left(90)
    alex.end_fill()


alex.penup() #new position
alex.right(180)
alex.forward(250)
alex.pendown()

cond = input("What do you want on your burger? the food you can put on your burger is chicken , cheese , lettuce , tomato , or nothing ?") 
if cond == "chicken":
    alex.color("black", "orange")#bread
    alex.begin_fill()
    alex.left(90)
    alex.circle(40, 180)
    alex.left(90)
    alex.end_fill()

    alex.color("black", "brown")#chicken
    alex.begin_fill()
    alex.forward(90)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()
    
if cond == "cheese":
    alex.color("black", "orange")#bread
    alex.begin_fill()
    alex.left(90)
    alex.circle(40, 180)
    alex.left(90)
    alex.end_fill()
    
    alex.color("black", "yellow")#cheese
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "lettuce":
    alex.color("black", "orange")#bread
    alex.begin_fill()
    alex.left(90)
    alex.circle(40, 180)
    alex.left(90)
    alex.end_fill()

    alex.color("black", "green")#lettuce
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "tomato":
    alex.color("black", "orange")#bread
    alex.begin_fill()
    alex.left(90)
    alex.circle(40, 180)
    alex.left(90)
    alex.end_fill()

    alex.color("black", "red")#tomato
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "nothing":
    alex.color("black", "orange")#bread
    alex.begin_fill()
    alex.left(90)
    alex.circle(40, 180)
    alex.left(90)
    alex.end_fill()
 
    alex.color("black", "orange")#top bread
    alex.begin_fill()
    alex.right(90)
    alex.circle(40, 180)
    alex.left(90)
    alex.forward(80)
    alex.end_fill()
    alex.color('red')
    style = ('Lauren', 15, 'bold', 'italic')
    alex.penup()
    alex.right(90)
    alex.forward(100)
    alex.pendown()
    alex.write('enjoy your nothing burger', font=style, align='center')
    alex.hideturtle()
    turtle.done()

    

cond = input("What do you want next on your burger? chicken , cheese , lettuce , tomato , or nothing ?: ")
if cond == "chicken":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "brown")#chicken
    alex.begin_fill()
    alex.forward(90)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "cheese":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "yellow")#cheese
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "lettuce":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "green")#lettuce
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "tomato":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "red")#tomato
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "nothing":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(40)
    alex.left(90)
    alex.color("black", "orange")#top bread
    alex.begin_fill()
    alex.circle(40, 180)
    alex.right(90)
    alex.end_fill()
    alex.color('red')
    style = ('Lauren', 15, 'bold', 'italic')
    alex.penup()
    alex.right(90)
    alex.forward(100)
    alex.pendown()
    alex.write('enjoy your burger', font=style, align='center')
    turtle.done()

cond = input("What do you want next on your burger? chicken , cheese , lettuce , tomato , or nothing ?")
if cond == "chicken":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "brown")#chicken
    alex.begin_fill()
    alex.forward(90)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "cheese":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "yellow")#cheese
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "lettuce":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "green")#lettuce
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "tomato":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "red")#tomato
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "nothing":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(40)
    alex.left(90)
    alex.color("black", "orange")#top bread
    alex.begin_fill()
    alex.circle(40, 180)
    alex.right(90)
    alex.end_fill()
    alex.color('red')
    style = ('Lauren', 15, 'bold', 'italic')
    alex.penup()
    alex.right(90)
    alex.forward(100)
    alex.pendown()
    alex.write('enjoy your burger', font=style, align='center')
    turtle.done()

cond = input("What do you want next on your burger? chicken , cheese , lettuce , tomato , or nothing ?")
if cond == "chicken":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "brown")#chicken
    alex.begin_fill()
    alex.forward(90)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "cheese":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "yellow")#cheese
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "lettuce":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "green")#lettuce
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "tomato":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(45)
    alex.left(90)
    alex.left(90)
    alex.color("black", "red")#tomato
    alex.begin_fill()
    alex.forward(95)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(100)
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.end_fill()

if cond == "nothing":
    alex.right(90)
    alex.forward(10)
    alex.right(90)
    alex.forward(40)
    alex.left(90)
    alex.color("black", "orange")#top bread
    alex.begin_fill()
    alex.circle(40, 180)
    alex.right(90)
    alex.end_fill()
    alex.color('red')
    style = ('Lauren', 15, 'bold', 'italic')
    alex.penup()
    alex.right(90)
    alex.forward(100)
    alex.pendown()
    alex.write('enjoy your burger', font=style, align='center')
    turtle.done()


alex.right(90)
alex.forward(10)
alex.right(90)
alex.forward(40)
alex.left(90)
alex.color("black", "orange")#top bread
alex.begin_fill()
alex.circle(40, 180)
alex.right(90)
alex.end_fill()
print("enjoy your burger.")


    


    

    
    
    

    
    
    
    
    
    
